# Generated by Django 5.1.15 on 2026-05-15 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Назва (EN)')),
                ('color', models.CharField(default='#6b7280', max_length=10, verbose_name='Колір (HEX)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('notify_customer', models.BooleanField(default=False, verbose_name='Сповіщати клієнта')),
            ],
            options={
                'verbose_name': 'Статус замовлення',
                'verbose_name_plural': 'Статуси замовлень',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('delivery_type', models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('ukrposhta', 'Укрпошта'), ('pickup', 'Самовивіз')], default='nova_poshta', max_length=20, verbose_name='Доставка')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='Місто')),
                ('city_ref', models.CharField(blank=True, max_length=50, verbose_name='НП ref міста')),
                ('warehouse', models.CharField(blank=True, max_length=255, verbose_name='Відділення')),
                ('warehouse_ref', models.CharField(blank=True, max_length=50, verbose_name='НП ref відділення')),
                ('payment_method', models.CharField(choices=[('card', 'Картка'), ('cod', 'Післяплата'), ('google_pay', 'Google Pay'), ('apple_pay', 'Apple Pay'), ('installment', 'Розстрочка')], default='card', max_length=20, verbose_name='Оплата')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('payment_id', models.CharField(blank=True, max_length=255, verbose_name='ID транзакції')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Доставка')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Знижка')),
                ('bonus_used', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бонусів використано')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('ttn', models.CharField(blank=True, max_length=100, verbose_name='ТТН')),
                ('fiscal_check_url', models.URLField(blank=True, verbose_name='Чек')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупець')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Назва товару')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна')),
                ('qty', models.PositiveSmallIntegerField(default=1, verbose_name='Кількість')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиція',
                'verbose_name_plural': 'Позиції',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('notify_customer', models.BooleanField(default=False, verbose_name='Сповіщено клієнта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order', verbose_name='Замовлення')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Запис статусу',
                'ordering': ['-created_at'],
            },
        ),
    ]
