# Generated by Django 5.1.15 on 2026-05-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Після переходу в цей статус нараховуються бонуси за замовлення', verbose_name='Завершений (нараховувати бонуси)'),
        ),
    ]
