# Generated by Django 5.1.15 on 2026-05-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_orderstatus_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='Індекс (УкрПошта)'),
        ),
        migrations.AddField(
            model_name='order',
            name='up_barcode',
            field=models.CharField(blank=True, max_length=100, verbose_name='Штрихкод УкрПошти'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ttn',
            field=models.CharField(blank=True, max_length=100, verbose_name='ТТН (НП)'),
        ),
    ]
