# Generated by Django 5.1.15 on 2026-07-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_seed_order_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_error',
            field=models.CharField(blank=True, help_text='Остання помилка API перевізника при створенні ТТН; очищається при успіху.', max_length=500, verbose_name='Помилка створення відправлення'),
        ),
    ]
