# Generated by Django 5.1.15 on 2026-07-20 09:06

from django.db import migrations, models


def remap_ukrposhta_orders(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(delivery_type="ukrposhta").update(delivery_type="nova_poshta")


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_shipping_error"),
    ]

    operations = [
        migrations.RunPython(remap_ukrposhta_orders, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="order",
            name="postcode",
        ),
        migrations.RemoveField(
            model_name="order",
            name="up_barcode",
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("nova_poshta", "Нова Пошта"), ("pickup", "Самовивіз")],
                default="nova_poshta",
                max_length=20,
                verbose_name="Доставка",
            ),
        ),
    ]
