# Generated by Django 5.1.15 on 2026-05-15 10:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Прізвище')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата реєстрації')),
                ('bonus_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бонусний баланс')),
                ('consent_email', models.BooleanField(default=True, verbose_name='Email-розсилка')),
                ('consent_sms', models.BooleanField(default=True, verbose_name='SMS-розсилка')),
                ('push_subscription_json', models.TextField(blank=True, verbose_name='Push-підписка')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Покупець',
                'verbose_name_plural': 'Покупці',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Наприклад: Дім, Робота', max_length=50, verbose_name='Мітка')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('city', models.CharField(max_length=150, verbose_name='Місто')),
                ('city_ref', models.CharField(blank=True, max_length=50, verbose_name='НП ref міста')),
                ('delivery_type', models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('ukrposhta', 'Укрпошта'), ('pickup', 'Самовивіз')], default='nova_poshta', max_length=20, verbose_name='Тип доставки')),
                ('warehouse', models.CharField(blank=True, max_length=255, verbose_name='Відділення')),
                ('warehouse_ref', models.CharField(blank=True, max_length=50, verbose_name='НП ref відділення')),
                ('is_default', models.BooleanField(default=False, verbose_name='За замовчуванням')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Покупець')),
            ],
            options={
                'verbose_name': 'Адреса',
                'verbose_name_plural': 'Адреси',
                'ordering': ['-is_default', 'id'],
            },
        ),
    ]
