# Generated by Django 5.1.15 on 2026-05-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='viber_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Viber ID'),
        ),
    ]
