# Generated by Django 5.1.15 on 2026-06-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_add_messenger_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Монети СвітПК'),
        ),
    ]
