# Generated by Django 5.1.15 on 2026-07-20 09:06

from django.db import migrations, models


def remap_ukrposhta_addresses(apps, schema_editor):
    Address = apps.get_model("customers", "Address")
    Address.objects.filter(delivery_type="ukrposhta").update(delivery_type="nova_poshta")


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_alter_customer_bonus_balance"),
    ]

    operations = [
        migrations.RunPython(remap_ukrposhta_addresses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="address",
            name="delivery_type",
            field=models.CharField(
                choices=[("nova_poshta", "Нова Пошта"), ("pickup", "Самовивіз")],
                default="nova_poshta",
                max_length=20,
                verbose_name="Тип доставки",
            ),
        ),
    ]
