# Generated by Django 5.1.15 on 2026-05-15 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('device', models.CharField(max_length=255, verbose_name='Пристрій')),
                ('description', models.TextField(verbose_name='Опис несправності')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В роботі'), ('waiting_parts', 'Очікує запчастин'), ('ready', 'Готова до видачі'), ('done', 'Видана'), ('cancelled', 'Скасована')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('technician_notes', models.TextField(blank=True, verbose_name='Примітки техніка')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Орієнтовна вартість')),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фактична вартість')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, verbose_name='Telegram Chat ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service', verbose_name='Послуга')),
            ],
            options={
                'verbose_name': 'Заявка сервісного центру',
                'verbose_name_plural': 'Заявки сервісного центру',
                'ordering': ['-created_at'],
            },
        ),
    ]
