# Generated by Django 5.1.15 on 2026-05-18 11:11

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_add_servicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Опис (EN)'),
        ),
    ]
