# Generated by Django 5.1.15 on 2026-07-20 09:06

from django.db import migrations, models


def remap_ukrposhta_warranty(apps, schema_editor):
    WarrantyClaim = apps.get_model("services", "WarrantyClaim")
    WarrantyClaim.objects.filter(delivery_service="ukrposhta").update(delivery_service="other")


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_priceitem_unit_excludes_materials"),
    ]

    operations = [
        migrations.RunPython(remap_ukrposhta_warranty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="warrantyclaim",
            name="delivery_service",
            field=models.CharField(
                blank=True,
                choices=[("nova_poshta", "Нова Пошта"), ("other", "Інша")],
                max_length=20,
                verbose_name="Служба доставки",
            ),
        ),
    ]
