# Generated by Django 5.1.15 on 2026-05-15 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Код')),
                ('discount_type', models.CharField(choices=[('percent', 'Відсоток'), ('fixed', 'Фіксована сума')], default='percent', max_length=10, verbose_name='Тип')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Знижка')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мін. замовлення')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = необмежено', verbose_name='Макс. використань')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Використано')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Дійсний з')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Дійсний до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
            },
        ),
        migrations.CreateModel(
            name='BonusTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'Нарахування'), ('spend', 'Списання'), ('adjust', 'Коригування'), ('birthday', 'Бонус ДН')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс після')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_transactions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
            options={
                'verbose_name': 'Бонусна транзакція',
                'verbose_name_plural': 'Бонусні транзакції',
                'ordering': ['-created_at'],
            },
        ),
    ]
