# Generated by Django 5.1.15 on 2026-07-08 10:08

from django.conf import settings
from django.db import migrations, models


def guard_no_duplicate_earn(apps, schema_editor):
    """Fail loudly with actionable order IDs instead of a cryptic constraint error.

    We never auto-delete/merge BonusTransaction rows here — it's a financial
    ledger and balance_after is a running total, so silently removing "extra"
    earn rows could desync a customer's balance history. If duplicates exist,
    stop the migration and let a human reconcile them first.
    """
    BonusTransaction = apps.get_model("loyalty", "BonusTransaction")
    from django.db.models import Count

    dupes = (
        BonusTransaction.objects.filter(transaction_type="earn", order__isnull=False)
        .values("order_id")
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
        .values_list("order_id", "cnt")
    )
    dupes = list(dupes)
    if dupes:
        details = ", ".join(f"order #{oid} ({cnt}x)" for oid, cnt in dupes)
        raise RuntimeError(
            "loyalty 0004: duplicate 'earn' BonusTransaction rows found for "
            f"{len(dupes)} order(s): {details}. Resolve manually (merge/void extra "
            "rows via admin, adjusting balance_after accordingly) before re-running "
            "this migration — the unique constraint cannot be added while duplicates exist."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_coin_loyalty'),
        ('orders', '0006_seed_order_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(guard_no_duplicate_earn, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='bonustransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False), ('transaction_type', 'earn')), fields=('order', 'transaction_type'), name='loyalty_one_earn_per_order'),
        ),
    ]
