# Generated by Django 5.1.15 on 2026-05-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Зображення')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='banners/mobile/', verbose_name='Зображення (mobile)')),
                ('link', models.URLField(blank=True, verbose_name='Посилання')),
                ('position', models.CharField(choices=[('home', 'Головна'), ('category', 'Каталог')], default='home', max_length=20, verbose_name='Позиція')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банери',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('description_en', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='Зображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Початок')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Кінець')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='catalog.product', verbose_name='Товари')),
            ],
            options={
                'verbose_name': 'Акція',
                'verbose_name_plural': 'Акції',
                'ordering': ['-date_start', 'sort_order'],
            },
        ),
    ]
