# Generated by Django 5.1.15 on 2026-06-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_remodel_promotion_product_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Ціна товару до початку акції. Відновлюється автоматично після деактивації.', max_digits=12, null=True, verbose_name='Ціна до акції'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Залиште порожнім щоб не змінювати ціну товару. При збереженні — ціна товару стане акційною, стара ціна збережеться автоматично.', max_digits=12, null=True, verbose_name='Акційна ціна'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Опис (EN)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(help_text='Дата завершення. Таймер показує залишок до цього моменту.', verbose_name='Кінець'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Якщо вимкнено — акція не показується незалежно від дат.', verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(help_text='Дата і час, коли акція починається.', verbose_name='Початок'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Підзаголовок акції (EN)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title_uk',
            field=models.CharField(blank=True, default='', help_text="Необов'язково. Наприклад: «Знижки до Дня Матері». Не пишіть «Акція» — це слово вже показується на значку товару.", max_length=200, verbose_name='Підзаголовок акції'),
        ),
    ]
