# Generated by Django 5.1.15 on 2026-05-15 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30, verbose_name='Провайдер')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('success', 'Успішно'), ('failed', 'Невдало'), ('refunded', 'Повернуто')], default='pending', max_length=20, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума')),
                ('currency', models.CharField(default='UAH', max_length=5, verbose_name='Валюта')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='ID транзакції')),
                ('raw_response', models.JSONField(default=dict, verbose_name='Відповідь провайдера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Платіж',
                'verbose_name_plural': 'Платежі',
                'ordering': ['-created_at'],
            },
        ),
    ]
