# Generated by Django 5.1.15 on 2026-05-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Format: liqpay_{payment_id}_{status}', max_length=120, null=True, unique=True, verbose_name='Ключ ідемпотентності'),
        ),
    ]
