# Generated by Django 5.1.15 on 2026-05-15 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovaPoshtaCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Місто')),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('ref', models.CharField(max_length=50, unique=True, verbose_name='Ref')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Область')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Місто НП',
                'verbose_name_plural': 'Міста НП',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NovaPoshtaWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Відділення')),
                ('ref', models.CharField(max_length=50, unique=True, verbose_name='Ref')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Номер')),
                ('type', models.CharField(blank=True, max_length=50, verbose_name='Тип')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='shipping.novaposhtacity')),
            ],
            options={
                'verbose_name': 'Відділення НП',
                'verbose_name_plural': 'Відділення НП',
                'ordering': ['number'],
            },
        ),
    ]
