#!/usr/bin/env python3
"""Flatten css/app.css @imports into one file — removes 25+ render-blocking CSS requests."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSS_DIR = ROOT / "static" / "css"
ENTRY = CSS_DIR / "app.css"
OUTPUT = CSS_DIR / "app.bundled.css"

_IMPORT_RE = re.compile(
    r'@import\s+(?:url\()?["\']?([^"\')\s;]+)["\']?\)?(?:\s+layer\([^)]+\))?\s*;',
    re.MULTILINE,
)


def _resolve_import(import_path: str, base_file: Path) -> Path:
    resolved = (base_file.parent / import_path).resolve()
    if not resolved.is_file():
        raise FileNotFoundError(f"Missing CSS import: {import_path} (from {base_file})")
    return resolved


def _inline_file(path: Path, seen: set[Path]) -> list[str]:
    if path in seen:
        return []
    seen.add(path)
    text = path.read_text(encoding="utf-8")
    parts: list[str] = []
    last = 0
    for match in _IMPORT_RE.finditer(text):
        prefix = text[last : match.start()].strip()
        if prefix:
            parts.append(prefix)
        parts.extend(_inline_file(_resolve_import(match.group(1), path), seen))
        last = match.end()
    suffix = text[last:].strip()
    if suffix:
        parts.append(suffix)
    return parts


def build_bundle() -> Path:
    if not ENTRY.is_file():
        raise FileNotFoundError(ENTRY)

    raw = ENTRY.read_text(encoding="utf-8")
    header_lines: list[str] = []
    body_start = 0
    for match in _IMPORT_RE.finditer(raw):
        prefix = raw[body_start : match.start()].strip()
        if prefix:
            header_lines.append(prefix)
        body_start = match.end()
    footer = raw[body_start:].strip()

    seen: set[Path] = set()
    chunks: list[str] = []
    for match in _IMPORT_RE.finditer(raw):
        chunks.extend(_inline_file(_resolve_import(match.group(1), ENTRY), seen))

    header = "/* Generated by scripts/build_css_bundle.py — do not edit by hand */\n"
    if header_lines:
        header += "\n\n".join(header_lines) + "\n\n"
    if chunks:
        header += "\n\n".join(chunks) + "\n\n"
    if footer:
        header += footer + "\n"

    OUTPUT.write_text(header, encoding="utf-8")
    return OUTPUT


def main() -> int:
    out = build_bundle()
    size_kb = out.stat().st_size / 1024
    print(f"Wrote {out.relative_to(ROOT)} ({size_kb:.1f} KiB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
