# Generated by Django 5.1.15 on 2026-05-15 10:24

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Вміст')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Вміст (EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Інфосторінка',
                'verbose_name_plural': 'Інфосторінки',
                'ordering': ['sort_order'],
            },
        ),
    ]
