# Generated by Django 5.1.15 on 2026-06-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('order_number', models.CharField(max_length=64, verbose_name='Номер замовлення')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('reason', models.CharField(choices=[('return', 'Повернення'), ('warranty', 'Гарантія')], max_length=20, verbose_name='Причина звернення')),
                ('description', models.TextField(blank=True, verbose_name='Опис проблеми')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='returns/', verbose_name='Фото товару')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В обробці'), ('done', 'Завершена'), ('rejected', 'Відхилена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Заявка на повернення',
                'verbose_name_plural': 'Заявки на повернення',
                'ordering': ['-created_at'],
            },
        ),
    ]
