# Generated by Django 5.1.15 on 2026-05-15 10:24

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('oc_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='OC ID')),
            ],
            options={
                'verbose_name': 'Група атрибутів',
                'verbose_name_plural': 'Групи атрибутів',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('oc_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='OC ID')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FilterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('oc_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='OC ID')),
            ],
            options={
                'verbose_name': 'Група фільтрів',
                'verbose_name_plural': 'Групи фільтрів',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='Старий шлях')),
                ('new_path', models.CharField(max_length=500, verbose_name='Новий шлях')),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301'), (302, '302')], default=301, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Редірект',
                'verbose_name_plural': 'Редіректи',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('oc_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='OC ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.attributegroup', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибути',
                'ordering': ['group__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Зображення')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='Іконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_top', models.BooleanField(default=False, verbose_name='Показати у навігації')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_title_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=500, verbose_name='SEO description')),
                ('seo_description_uk', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO description')),
                ('seo_description_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO description')),
                ('oc_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='OC ID')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Назва')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('oc_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='OC ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='catalog.filtergroup', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Фільтр',
                'verbose_name_plural': 'Фільтри',
                'ordering': ['group__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarkupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Націнка %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Вищий = важливіший', verbose_name='Пріоритет')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Правило націнки',
                'verbose_name_plural': 'Правила націнки',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Зовнішній ID')),
                ('source', models.CharField(choices=[('brain', 'Brain API'), ('kancmaster', 'Kancmaster XML'), ('manual', 'Вручну')], default='manual', max_length=20, verbose_name='Джерело')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Артикул')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Модель')),
                ('oc_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='OC ID')),
                ('name', models.CharField(max_length=500, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=500, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=500, null=True, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('short_description_uk', models.TextField(blank=True, null=True, verbose_name='Короткий опис')),
                ('short_description_en', models.TextField(blank=True, null=True, verbose_name='Короткий опис')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_title_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=500, verbose_name='SEO description')),
                ('seo_description_uk', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO description')),
                ('seo_description_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стара ціна')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Закупівельна ціна')),
                ('stock', models.IntegerField(default=0, verbose_name='Залишок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показувати')),
                ('hide_if_out_of_stock', models.BooleanField(default=False, verbose_name='Приховати без залишку')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_hit', models.BooleanField(default=False, verbose_name='Хіт продажів')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Основне фото')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='URL фото (зовнішній)')),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата додавання')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('viewed', models.PositiveIntegerField(default=0, verbose_name='Переглядів')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand', verbose_name='Бренд')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='catalog.category', verbose_name='Категорії')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Значення')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attribute', verbose_name='Атрибут')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Атрибут товару',
                'verbose_name_plural': 'Атрибути товару',
            },
        ),
        migrations.CreateModel(
            name='ProductFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.filter', verbose_name='Фільтр')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фільтр товару',
                'verbose_name_plural': 'Фільтри товару',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='Зображення')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='URL (зовнішній)')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товару',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SeoUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(default='uk', max_length=5, verbose_name='Мова')),
                ('query', models.CharField(db_index=True, max_length=255, verbose_name='OC query')),
                ('keyword', models.SlugField(max_length=500, verbose_name='Keyword')),
                ('oc_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='OC seo_url_id')),
            ],
            options={
                'verbose_name': 'SEO URL (OC)',
                'verbose_name_plural': 'SEO URLs (OC)',
                'unique_together': {('language_code', 'query')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['source', 'external_id'], name='catalog_pro_source_57687d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_visible', 'stock'], name='catalog_pro_is_visi_f2be60_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_new'], name='catalog_pro_is_new_087fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_hit'], name='catalog_pro_is_hit_d36eb0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='productfilter',
            unique_together={('product', 'filter')},
        ),
    ]
