# Generated by Django 5.1.15 on 2026-05-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kancmaster_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Kancmaster назва'),
        ),
    ]
