# Generated by Django 5.1.15 on 2026-05-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_cleanup_gallery_and_unique_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order', 'pk'], 'verbose_name': 'Фото товару', 'verbose_name_plural': 'Фото товару'},
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_en',
            field=models.TextField(null=True, verbose_name='Значення'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_uk',
            field=models.TextField(null=True, verbose_name='Значення'),
        ),
    ]
