# Generated by Django 5.1.15 on 2026-06-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_unescape_catalog_text_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_product_name_trgm',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_product_sku_trgm',
        ),
    ]
