# Generated by Django 5.1.15 on 2026-07-08 10:19

from django.db import migrations, models


def backfill_has_display_image(apps, schema_editor):
    """Заповнити денормалізований прапорець за повним предикатом gallery."""
    from apps.catalog.gallery import recompute_has_display_image

    updated = recompute_has_display_image()
    if updated:
        print(f"catalog 0020: has_display_image backfilled for {updated} product(s)")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_product_price_feed_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_prod_vis_price',
            old_name='catalog_product_visible_price_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_prod_vis_stock_price',
            old_name='catalog_product_visible_stock_price_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='has_display_image',
            field=models.BooleanField(default=False, editable=False, verbose_name='Є фото для вітрини'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_visible', 'has_display_image'], name='catalog_prod_vis_img_idx'),
        ),
        migrations.RunPython(backfill_has_display_image, migrations.RunPython.noop),
    ]
