# Generated by Django 5.1.15 on 2026-07-08 10:54

from django.db import migrations, models


def raise_prices_to_purchase_floor(apps, schema_editor):
    """Підняти наявні збиткові ціни до закупівельної, щоб constraint застосувався."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE catalog_product SET price = purchase_price "
            "WHERE purchase_price > 0 AND price < purchase_price"
        )
        if cursor.rowcount:
            print(f"catalog 0021: raised {cursor.rowcount} below-cost price(s) to purchase floor")
        # old_price нижче нової ціни не має сенсу — прибираємо
        cursor.execute(
            "UPDATE catalog_product SET old_price = NULL "
            "WHERE old_price IS NOT NULL AND old_price <= price"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_rename_catalog_product_visible_price_idx_catalog_prod_vis_price_and_more'),
    ]

    operations = [
        migrations.RunPython(raise_prices_to_purchase_floor, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__isnull', True), ('purchase_price__lte', 0), ('price__gte', models.F('purchase_price')), _connector='OR'), name='catalog_product_price_above_cost'),
        ),
    ]
